### ISSUE TITLE
Incompatible with Visual Studio Tools for Unity

### ISSUE THREAD

**Issue by tgaldi** [viacheslav-lozinskyi/MetaProject#12] opened 2021-03-15 18:02 UTC
Selecting Debug->Start Debugging does not start the debugger.

It will work the very first time after I restart my machine, but after stopping debugging it will not work again.

![iw7nTotOtQ](https://user-images.githubusercontent.com/17083706/111199420-fa8c0100-8596-11eb-971e-d70efd6b1bb4.gif)

**Comment by SpiritV** [comment] 2021-03-15 18:11
Thank you for the reported bug.

However even in captured video I have open questions:
1. I don't see working MetaProject. Is it installed and enabled in that time?
2. I don't see any opened solution. Absolutely unclear what should be started?
3. Absolutely unclear which result is expected?

**Comment by tgaldi** [comment] 2021-03-15 18:18
![image](https://user-images.githubusercontent.com/17083706/111201199-ecd77b00-8598-11eb-9f98-3815703762ba.png)

Without MetaProject:
![YNW8D0Xkcp](https://user-images.githubusercontent.com/17083706/111201571-4475e680-8599-11eb-878e-2608a1fbfaff.gif)

**Comment by viacheslav-lozinskyi** [comment] 2021-03-15 18:27
Ok, I see that something is started, but I still don't see MetaProject output tool.

Also from this example I don't see any problem. You start application, and after that you stop application.
Where is a problem?

**Comment by tgaldi** [comment] 2021-03-15 18:27
I cannot start debugging with metaproject enabled.

**Comment by viacheslav-lozinskyi** [comment] 2021-03-15 18:29
Could you make video with opened MetaProject tool and starting of your application?

**Comment by tgaldi** [comment] 2021-03-15 18:33
The first time it is enabled and debugging is started then stopped:
![image](https://user-images.githubusercontent.com/17083706/111203366-4d67b780-859b-11eb-8ca1-a1604c40249f.png)

Afterwards:
![CNMr2zGBkn](https://user-images.githubusercontent.com/17083706/111203411-5a84a680-859b-11eb-907a-036cd83f05ee.gif)

**Comment by viacheslav-lozinskyi** [comment] 2021-03-15 18:39
Now I see the problem.

I will make test application on Unity and will try to reproduce it.
If I can reproduce the bug, it will be fixed in the next release.

Thank you for the reported bug.

**Comment by viacheslav-lozinskyi** [comment] 2021-03-15 20:37
![vs unity sample](https://user-images.githubusercontent.com/51988029/111217836-ac9aeb80-85de-11eb-8082-39df3c3d1b44.gif)

I can't reproduce this bug.
Unity example is working fine.

**Comment by tgaldi** [comment] 2021-03-15 23:40
Are you using the Unity Editor? The game should not play when you start debugging. Also, it does work the first time, but after stopping debugging and starting again it no longer works.

**Comment by viacheslav-lozinskyi** [comment] 2021-03-16 06:31
I took example from Unity Editor, and made Visual Studio project from Unity project. After that I have opened this VS project and started/stopped it many times. It works correctly.

I didn't make such video just by reason that Git allow attach files to comment with maximal size 10Mb.

**Comment by viacheslav-lozinskyi** [comment] 2021-03-16 06:37
https://user-images.githubusercontent.com/51988029/111266121-c1a16a00-8632-11eb-8559-454dbe21aec6.mp4

This video demonstrates that it works when start application many times

**Comment by tgaldi** [comment] 2021-03-16 13:03
I've done some more testing and it seems to be related to starting and stopping without hitting play in the editor:

![qG6mJM22oj](https://user-images.githubusercontent.com/17083706/111313158-62ddef80-8636-11eb-9572-cb8692312c0f.gif)

**Comment by viacheslav-lozinskyi** [comment] 2021-03-16 15:13
I will try to reproduce it, thank you for the information.

**Comment by viacheslav-lozinskyi** [comment] 2021-07-10 07:41
MetaProject 2.0.1 is released.
Could you check is this bug fixed?

**Closed as completed** 2021-09-09 16:11 UTC
Labels: bug
